# Generated by Django 4.2.7 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_expand_submission_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprogresssnapshot',
            name='domain_weights',
            field=models.JSONField(blank=True, default=dict, help_text='Weighted domain profile for recommendations (domain id str -> percent).'),
        ),
    ]
