# Generated by Django 4.2.7 on 2026-04-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_studentprogresssnapshot_domain_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprojectassignment',
            name='recommendation_source',
            field=models.CharField(blank=True, choices=[('COLD_START', 'Cold start'), ('CONTENT_BASED', 'Content based'), ('COLLABORATIVE', 'Collaborative')], help_text='FR3 feed: cold start, tag/content similarity, or collaborative filtering.', max_length=20, null=True),
        ),
    ]
