# Generated by Django 4.2.7 on 2026-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_submission_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Required for all submission types; CODE must upload a ZIP file.', null=True, upload_to='submissions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='studentprojectassignment',
            name='recommendation_source',
            field=models.CharField(blank=True, choices=[('COLD_START', 'Cold start'), ('CONTENT_BASED', 'Content based'), ('COLLABORATIVE', 'Collaborative')], help_text='Cold start, content/tag match, or collaborative filtering.', max_length=20, null=True),
        ),
    ]
