# Generated by Django 4.2.7 on 2026-03-27 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0006_alter_assessmentquestion_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='recommendation_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Rule-based ranked domains, explanation, method (FR2).'),
        ),
        migrations.CreateModel(
            name='ComposedAssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composed_assessment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'composed_assessment_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
