# Generated by Django 4.2.7 on 2026-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_studentassessmentattempt_recommendation_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='recommendation_meta',
            field=models.JSONField(blank=True, default=dict, help_text='FR2: ranked_domains, weighted_domain_profile, ML primary, method, explanation.'),
        ),
    ]
