# Generated by Django 4.2.7 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_studentassessmentattempt_recommendation_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='recommendation_meta',
            field=models.JSONField(blank=True, default=dict, help_text='ranked_domains, weighted_domain_profile, ml primary, method, explanation.'),
        ),
    ]
